services:
  web:
    build: .
    container_name: roshan_web
    command: gunicorn roshan_news.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always

  celery:
    build: .
    container_name: roshan_celery
    command: celery -A roshan_news worker -l info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always

  celery_beat:
    build: .
    container_name: roshan_beat
    command: celery -A roshan_news beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always

  flower:
    build: .
    container_name: roshan_flower
    entrypoint: ["/app/wait-for-celery.sh"]
    command: celery -A roshan_news  flower --port=5555 --loglevel=debug
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    restart: always

  redis:
    image: redis:7
    container_name: roshan_redis
    ports:
      - "6379:6379"
    restart: always